#!/bin/bash

CURRENT_PATH="`( pwd )`"
INPUT_FILE="$1"
OUTPUT_FILE="${INPUT_FILE%%.*}_COG.${INPUT_FILE##*.}"
TEMP_FILE="${INPUT_FILE%%.*}_TEMP.${INPUT_FILE##*.}"


GREEN=`tput setaf 2`
NC=`tput sgr0`

echo "${GREEN}GDAL TRANSLATE: $INPUT_FILE -> $TEMP_FILE${NC}"
gdal_translate "$CURRENT_PATH/$INPUT_FILE" "$CURRENT_PATH/$TEMP_FILE" -co TILED=YES -co COMPRESS=PACKBITS -co BIGTIFF=YES
echo ${GREEN}"GDALADDO: 4 16 32${NC}"
gdaladdo -r near "$CURRENT_PATH/$TEMP_FILE" 4 16 32
echo "${GREEN}GDAL TRANSLATE: $TEMP_FILE -> $OUTPUT_FILE${NC}"
gdal_translate "$CURRENT_PATH/$TEMP_FILE" "$CURRENT_PATH/$OUTPUT_FILE" -co TILED=YES -co COMPRESS=DEFLATE -co ZLEVEL=3 -co COPY_SRC_OVERVIEWS=YES -co BIGTIFF=YES 
rm "$CURRENT_PATH/$TEMP_FILE"
# rm "$CURRENT_PATH/$INPUT_FILE"
